### ISSUE TITLE
ls: An unexpected error occurred: 'NoneType' object has no attribute 'subfolders'.

### ISSUE THREAD

**Issue by groner** [Keeper-Security/Commander#429]
After upgrading to 16.1.3, things aren't working unless I run `sync-down`. `whoami` seems to do the trick too.

```
: kai; keeper shell


  _  __  
 | |/ /___ ___ _ __  ___ _ _ 
 | ' </ -_) -_) '_ \/ -_) '_|
 |_|\_\___\___| .__/\___|_|
 v16.1.3      |_|

 password manager & digital vault

Logging in to Keeper Commander
Enter password for REDACTED
Password: 
'encrypted_ecc_private_key'
Keeper> ls                                     
An unexpected error occurred: 'NoneType' object has no attribute 'subfolders'. Toggle debug to print traceback
Keeper> sync-down                              
Syncing...
Decrypted [NNN] record(s)
```

I'm not sure what the `'encrypted_ecc_private_key'` message is telling me.

Commands `ls`, `cc`, `tree`, `cd`, `get` all fail with similar AttributeErrors.

**Comment by groner** [comment]
Closing because this seems to be fixed in v16.1.6.
