### ISSUE TITLE
Release 4.77 is broken

### ISSUE THREAD

**Issue by martijndegouw** [Keeper-Security/Commander#354]
Hi,

After upgrading keepercommander from 4.67 to 4.77 my project does not start anymore:
```Traceback (most recent call last):
  File "/data/projects/lnx/mdg/keeperproject/venv/bin/uvicorn", line 10, in <module>
    sys.exit(main())
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/uvicorn/main.py", line 362, in main
    run(**kwargs)
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./keeperproject/main.py", line 8, in <module>
    from keeperproject.keeper.vault import Vault
  File "./keeperproject/keeper/vault.py", line 7, in <module>
    from keepercommander import api as keeper
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/keepercommander/api.py", line 23, in <module>
    from . import rest_api, APIRequest_pb2 as proto, loginv3
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/keepercommander/loginv3.py", line 25, in <module>
    from . import cli
  File "/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/keepercommander/cli.py", line 29, in <module>
    from .loginv3 import permissions_error_msg
ImportError: cannot import name 'permissions_error_msg' from 'keepercommander.loginv3' (/data/projects/lnx/mdg/keeperproject/venv/lib/python3.7/site-packages/keepercommander/loginv3.py)
```

Steps to reproduce:
```
$ python
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from keepercommander import api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/projects/lnx/mdg/keeperproxy/venv/lib/python3.7/site-packages/keepercommander/api.py", line 23, in <module>
    from . import rest_api, APIRequest_pb2 as proto, loginv3
  File "/data/projects/lnx/mdg/keeperproxy/venv/lib/python3.7/site-packages/keepercommander/loginv3.py", line 25, in <module>
    from . import cli
  File "/data/projects/lnx/mdg/keeperproxy/venv/lib/python3.7/site-packages/keepercommander/cli.py", line 29, in <module>
    from .loginv3 import permissions_error_msg
ImportError: cannot import name 'permissions_error_msg' from 'keepercommander.loginv3' (/data/projects/lnx/mdg/keeperproxy/venv/lib/python3.7/site-packages/keepercommander/loginv3.py)
>>>
```

**Comment by maksimu** [comment]
Hello @martijndegouw 
We have fixed the issue and release new version 4.78.
The root issue was the way older version of Python importing modules, it works well in Python 3.9 but in your case with Python 3.7.3 it was not able to import a variable from another file
